### ISSUE TITLE
Allow custom field on route definition

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trailpack-router#24]
It can be useful to allow custom field on route definition, for example it can be nice to do : 

```
      {
        method: ['GET'],
        title: 'My Title',
        description: 'My Description',
        keywords: 'My Keywords',
        path: '/default/info',
        handler: 'DefaultController.info'
      }
```

Like this on controllers we can retrieve and use this fields easily.

**Comment by tjwebb** [comment]
@jaumard hapijs already supports putting some extra stuff in the `config` object. Their docs (http://hapijs.com/api#route-options) mention these:

```
The following documentation options are also available when adding new routes (they are not available when setting defaults):

description - route description used for generating documentation (string).
notes - route notes used for generating documentation (string or array of strings).
tags - route tags used for generating documentation (array of strings).
```

**Comment by jaumard** [comment]
@tjwebb thanks didn't know this possibility :) but config object is very restrictive... And config is relative to the route, information can be relative to meta datas or views. For the same example I can use `description` but can't put `title` or `keywords` in it...

If I think on some useful possibilities for the this feature they are : 
* Generate an automatique sitemap (just but putting `sitemap:true` for example)
* Google Analytics tracking  (just but putting `tracking:true` with meta datas for example) 
* SEO (like my example)
* ACL (static ACL without `trailpack-permissions` cause for small project is not needed, by putting `allowed:["group1", "group2"]`

If I remember Express allow you to put everything you want on route definition, if hapi doesn't maybe we can do something about this. I think this functionality is useful.

**Comment by tjwebb** [comment]
> For the same example I can use description but can't put title or keywords in it

For any existing tool that would parse these route objects (they are the standard hapi format), those tools would have no idea what `title` and `description` mean. There's already a way to achieve what you want.

> If I think on some useful possibilities for the this feature they are :

For all of these use cases, and I think for trailpacks in general, they should prioritize configuration in their own config files rather than altering other config files.

With hapi, I think you also can put anything you want in the config object; the trailpack validator probably is being more restrictive. You could loosen this up by altering this file: https://github.com/trailsjs/trailpack-router/blob/master/lib/schemas/route.js

**Comment by jaumard** [comment]
@tjwebb I just made the test and hapi doesn't allow extra field under `config` only the same as `trailpack-router` allow. 

```
[1] "custom" is not allowed
    at Object.exports.contain.exports.reachTemplate.exports.assert.condition [as assert] (/Users/jaumard/Downloads/testTrails/node_modules/trailpack-hapi/node_modules/hapi/node_modules/hoek/lib/index.js:732:11)
    at Object.exports.apply (/Users/jaumard/Downloads/testTrails/node_modules/trailpack-hapi/node_modules/hapi/lib/schema.js:17:10)
    at new module.exports.internals.Route.options (/Users/jaumard/Downloads/testTrails/node_modules/trailpack-hapi/node_modules/hapi/lib/route.js:60:28)
    at internals.Connection._init.internals.Connection._start.internals.Connection._stop.internals.Connection._dispatch.internals.Connection.inject.internals.Connection._addRoute (/Users/jaumard/Downloads/testTrails/node_modules/trailpack-hapi/node_modules/hapi/lib/connection.js:370:19)
    at internals.Connection._init.internals.Connection._start.internals.Connection._stop.internals.Connection._dispatch.internals.Connection.inject.internals.Connection._route (/Users/jaumard/Downloads/testTrails/node_modules/trailpack-hapi/node_modules/hapi/lib/connection.js:362:18)
    at module.exports.internals.Plugin.internals.Plugin.register.internals.Plugin._apply (/Users/jaumard/Downloads/testTrails/node_modules/trailpack-hapi/node_modules/hapi/lib/plugin.js:575:14)
    at module.exports.internals.Plugin.internals.Plugin.register.internals.Plugin.route (/Users/jaumard/Downloads/testTrails/node_modules/trailpack-hapi/node_modules/hapi/lib/plugin.js:545:10)
    at /Users/jaumard/Downloads/testTrails/node_modules/trailpack-hapi/lib/server.js:43:40
    at arrayEach (/Users/jaumard/Downloads/testTrails/node_modules/lodash/lodash.js:482:11)
    at Function.forEach (/Users/jaumard/Downloads/testTrails/node_modules/lodash/lodash.js:7767:11)
    at Object.registerRoutes (/Users/jaumard/Downloads/testTrails/node_modules/trailpack-hapi/lib/server.js:43:7)
    at /Users/jaumard/Downloads/testTrails/node_modules/trailpack-hapi/index.js:44:20
    at process._tickDomainCallback (node.js:407:9)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:134:18)
    at node.js:962:3
```

I'm agree with you that each trailpack has to have own configuration except when it talk about routes... cause it's will be very difficult to duplicate routes to add informations about them. It's easier to add fields under `routes.js`
