### ISSUE TITLE
1.0.0-alpha-8 invalid path

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trailpack-router#25]
On trailpack-swagger I update 1.0.0-alpha-4 to 1.0.0-alpha-8 (the last version) and now I have this error on unit test : 
```
smokesignal logger: [ error ] 
 Error: Invalid path: /%7BparentModel%7D/%7BparentId%7D/%7BchildAttribute%7D/%7BchildId?%7D
    at Object.exports.contain.exports.reachTemplate.exports.assert.condition [as assert] (/Users/jaumard/IdeaProjects/trailpack-swagger/node_modules/hapi/node_modules/hoek/lib/index.js:732:11)
    at internals.Router.normalize.internals.Router.analyze (/Users/jaumard/IdeaProjects/trailpack-swagger/node_modules/hapi/node_modules/call/lib/index.js:184:10)
    at new module.exports.internals.Route.options (/Users/jaumard/IdeaProjects/trailpack-swagger/node_modules/hapi/lib/route.js:79:46)
    at internals.Connection._init.internals.Connection._start.internals.Connection._stop.internals.Connection._dispatch.internals.Connection.inject.internals.Connection._addRoute (/Users/jaumard/IdeaProjects/trailpack-swagger/node_modules/hapi/lib/connection.js:370:19)
    at internals.Connection._init.internals.Connection._start.internals.Connection._stop.internals.Connection._dispatch.internals.Connection.inject.internals.Connection._route (/Users/jaumard/IdeaProjects/trailpack-swagger/node_modules/hapi/lib/connection.js:362:18)
    at module.exports.internals.Plugin.internals.Plugin.register.internals.Plugin._apply (/Users/jaumard/IdeaProjects/trailpack-swagger/node_modules/hapi/lib/plugin.js:575:14)
    at module.exports.internals.Plugin.internals.Plugin.register.internals.Plugin.route (/Users/jaumard/IdeaProjects/trailpack-swagger/node_modules/hapi/lib/plugin.js:545:10)
    at /Users/jaumard/IdeaProjects/trailpack-swagger/node_modules/trailpack-hapi/lib/server.js:68:40
    at arrayEach (/Users/jaumard/IdeaProjects/trailpack-swagger/node_modules/lodash/lodash.js:473:11)
    at Function.forEach (/Users/jaumard/IdeaProjects/trailpack-swagger/node_modules/lodash/lodash.js:7607:11)
    at Object.registerRoutes (/Users/jaumard/IdeaProjects/trailpack-swagger/node_modules/trailpack-hapi/lib/server.js:68:7)
    at /Users/jaumard/IdeaProjects/trailpack-swagger/node_modules/trailpack-hapi/index.js:45:20
    at process._tickCallback (node.js:357:9)
smokesignal logger: [ error ] 
 The application attempted to shut down, but is not in a running state. Either it is in the process of shutting down, or did not start successfully. Trails will not attempt to shut down twice.
smokesignal logger: [ error ] 
 Try increasing the loglevel to "debug" to learn more
```
Is this normal  ?

**Comment by tjwebb** [comment]
This is resolved in latest.
