### ISSUE TITLE
TrailsApp fails on launching with `trailpack-router` version `3.1.x`

### ISSUE THREAD

**Issue by matteozambon89** [trailsjs/trailpack-router#64]
I've create a new project and when I'm installing the latest version of `trailpack-router` and run `npm test` I get the following error:
```
> mocha "test/*.js" --reporter spec



  1) "before all" hook
  2) "after all" hook

  0 passing (280ms)
  2 failing

  1)  "before all" hook:
     Error: Cannot find module 'call'
      at Function.Module._resolveFilename (module.js:485:15)
      at Function.Module._load (module.js:437:25)
      at Module.require (module.js:513:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> ({myProject}/node_modules/trailpack-router/lib/util.js:2:14)
      at Module._compile (module.js:569:30)
      at Object.Module._extensions..js (module.js:580:10)
      at Module.load (module.js:503:32)
      at tryModuleLoad (module.js:466:12)
      at Function.Module._load (module.js:458:3)
      at Module.require (module.js:513:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> ({myProject}/node_modules/trailpack-router/lib/index.js:2:16)
      at Module._compile (module.js:569:30)
      at Object.Module._extensions..js (module.js:580:10)
      at Module.load (module.js:503:32)
      at tryModuleLoad (module.js:466:12)
      at Function.Module._load (module.js:458:3)
      at Module.require (module.js:513:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> ({myProject}/node_modules/trailpack-router/index.js:2:13)
      at Module._compile (module.js:569:30)
      at Object.Module._extensions..js (module.js:580:10)
      at Module.load (module.js:503:32)
      at tryModuleLoad (module.js:466:12)
      at Function.Module._load (module.js:458:3)
      at Module.require (module.js:513:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> ({myProject}/config/main.js:27:5)
      at Module._compile (module.js:569:30)
      at Object.Module._extensions..js (module.js:580:10)
      at Module.load (module.js:503:32)
      at tryModuleLoad (module.js:466:12)
      at Function.Module._load (module.js:458:3)
      at Module.require (module.js:513:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> ({myProject}/config/index.js:13:16)
      at Module._compile (module.js:569:30)
      at Object.Module._extensions..js (module.js:580:10)
      at Module.load (module.js:503:32)
      at tryModuleLoad (module.js:466:12)
      at Function.Module._load (module.js:458:3)
      at Module.require (module.js:513:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> ({myProject}/index.js:4:18)
      at Module._compile (module.js:569:30)
      at Object.Module._extensions..js (module.js:580:10)
      at Module.load (module.js:503:32)
      at tryModuleLoad (module.js:466:12)
      at Function.Module._load (module.js:458:3)
      at Module.require (module.js:513:17)
      at require (internal/module.js:11:18)
      at Context.before ({myProject}/test/setup.js:6:30)
      at callFn ({myProject}/node_modules/mocha/lib/runnable.js:348:21)
      at Hook.Runnable.run ({myProject}/node_modules/mocha/lib/runnable.js:340:7)
      at next ({myProject}/node_modules/mocha/lib/runner.js:309:10)
      at Immediate.<anonymous> ({myProject}/node_modules/mocha/lib/runner.js:339:5)
      at runCallback (timers.js:781:20)
      at tryOnImmediate (timers.js:743:5)
      at processImmediate [as _immediateCallback] (timers.js:714:5)

  2)  "after all" hook:
     TypeError: Cannot read property 'stop' of undefined
      at Context.after ({myProject}/test/setup.js:11:20)
      at callFn ({myProject}/node_modules/mocha/lib/runnable.js:348:21)
      at Hook.Runnable.run ({myProject}/node_modules/mocha/lib/runnable.js:340:7)
      at next ({myProject}/node_modules/mocha/lib/runner.js:309:10)
      at Immediate.<anonymous> ({myProject}/node_modules/mocha/lib/runner.js:339:5)
      at runCallback (timers.js:781:20)
      at tryOnImmediate (timers.js:743:5)
      at processImmediate [as _immediateCallback] (timers.js:714:5)
```
here's my package.json
```
...
  "dependencies": {
    "async": "^2.5.0",
    "body-parser": "^1.17.2",
    "cookiejar": "^2.1.1",
    "express": "^5.0.0-alpha.2",
    "extend-object": "^1.0.0",
    "helmet": "^3.8.1",
    "moment": "^2.18.1",
    "passport-jwt": "^2.2.1",
    "passport-local": "^1.0.0",
    "sails-memory": "^0.10.7",
    "sails-mongo": "^0.12.2",
    "superagent": "^3.5.2",
    "trailpack-express": "^2.0.3",
    "trailpack-footprints": "^2.0.0",
    "trailpack-passport": "^2.1.5",
    "trailpack-repl": "^3.0.0-pre.1",
    "trailpack-router": "^3.1.0",
    "trailpack-swagger": "^2.0.5",
    "trailpack-waterline": "^2.0.0-rc2",
    "trails": "^2.0.2",
    "uuid": "^3.1.0",
    "winston": "^2.3"
  },
  "devDependencies": {
    "chai": "^4.1.0",
    "env-test": "^1.0.0",
    "eslint": "^4.3.0",
    "eslint-config-trails": "^3.0.0",
    "eslint-plugin-json": "^1.2.0",
    "eslint-plugin-markdown": "^1.0.0-beta.6",
    "eslint-plugin-mocha": "^4.11.0",
    "fixme": "^0.4.3",
    "mocha": "^3.4.2",
    "npm-check": "^5.4.5",
    "nsp": "^2.6.3",
    "supertest": "^3.0.0",
    "uglify-js": "^3.0.26"
  },
...
```
here's the `{myProject}/config/main.js`
```
25:  'packs': [
26:    require('trailpack-repl'),
27:    require('trailpack-router'),
28:    require('trailpack-express'),
29:    require('trailpack-waterline'),
30:    require('trailpack-passport'),
31:    require('trailpack-footprints'),
```
here's the `{myProject}/config/index.js`
```
08: exports.database = require('./database')
09: exports.env = require('./env')
10: exports.footprints = require('./footprints')
11: exports.i18n = require('./i18n')
12: exports.log = require('./log')
13: exports.main = require('./main')
14: exports.policies = require('./policies')
15: exports.routes = require('./routes')
16: exports.session = require('./session')
17: exports.views = require('./views')
18: exports.web = require('./web')
19: exports.passport = require('./passport')
20: exports.swagger = require('./swagger')
```
and here's the `{myProject}/index.js`
```
'use strict'

exports.pkg = require('./package')
exports.config = require('./config')
exports.api = require('./api')
```

**Comment by iwritesomecode** [comment]
I think the `call` module is to blame, as per #63.
